# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\translate.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_translateWindow(object):
    def setupUi(self, translateWindow):
        translateWindow.setObjectName("translateWindow")
        translateWindow.resize(800, 161)
        self.centralwidget = QtWidgets.QWidget(translateWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.translated_text_label = QtWidgets.QLabel(self.centralwidget)
        self.translated_text_label.setGeometry(QtCore.QRect(0, 0, 791, 131))
        self.translated_text_label.setOpenExternalLinks()
        font = QtGui.QFont()
        font.setPointSize(12)
        self.translated_text_label.setFont(font)
        self.translated_text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.translated_text_label.setObjectName("translated_text_label")
        translateWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(translateWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        translateWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(translateWindow)
        self.statusbar.setObjectName("statusbar")
        translateWindow.setStatusBar(self.statusbar)

        self.retranslateUi(translateWindow)
        QtCore.QMetaObject.connectSlotsByName(translateWindow)

    def retranslateUi(self, translateWindow):
        _translate = QtCore.QCoreApplication.translate
        translateWindow.setWindowTitle(_translate("translateWindow", "DeskTranslator - Translating"))
        self.translated_text_label.setText(_translate("translateWindow", "Translated text here"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    translateWindow = QtWidgets.QMainWindow()
    ui = Ui_translateWindow()
    ui.setupUi(translateWindow)
    translateWindow.show()
    sys.exit(app.exec_())
