"""Refresh the Windows environment lock from installed versions and PyPI hashes."""

from __future__ import annotations

import importlib.metadata
from pathlib import Path

import httpx
from packaging.tags import sys_tags
from packaging.utils import parse_wheel_filename


def main() -> None:
    supported = set(sys_tags())
    rows = []
    bootstrap = []
    packages = {
        d.metadata["Name"]: d.version
        for d in importlib.metadata.distributions()
        if d.metadata["Name"].lower() != "desktranslate"
    }
    packages["wheel"] = "0.46.3"
    with httpx.Client(timeout=30) as client:
        for name, version in sorted(packages.items(), key=lambda item: item[0].lower()):
            response = client.get(f"https://pypi.org/pypi/{name}/{version}/json")
            response.raise_for_status()
            artifacts = [
                f
                for f in response.json()["urls"]
                if f["filename"].endswith(".whl")
                and not f.get("yanked")
                and parse_wheel_filename(f["filename"])[3] & supported
            ]
            if not artifacts:
                artifacts = [
                    f
                    for f in response.json()["urls"]
                    if f["packagetype"] == "sdist" and not f.get("yanked")
                ]
            if not artifacts:
                raise RuntimeError(f"No compatible artifact for {name} {version}")
            row = f"{name}=={version}" + "".join(
                " " + chr(92) + "\n    --hash=sha256:" + f["digests"]["sha256"] for f in artifacts
            )
            rows.append(row)
            if name.lower() in {"pip", "setuptools", "wheel", "packaging"}:
                bootstrap.append(row)
    header = "# CPython 3.12 Windows x64 build environment. Generated by tools/lock_windows.py.\n"
    Path("requirements-windows.lock").write_text(header + "\n".join(rows) + "\n", encoding="utf-8")
    Path("requirements-bootstrap.lock").write_text(
        header + "\n".join(bootstrap) + "\n", encoding="utf-8"
    )
    print(f"Locked {len(rows)} distributions with upstream artifact hashes")


if __name__ == "__main__":
    main()
